# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.


Feature: Output Gherkin feature files

  Scenario: Output Gherkin feature files for behavior scenarios in an Architecture model.

      Given The "tests/calc/model/calculator.yaml" contains a valid architecture.
      When The aac app is run with the gen-gherkin-behaviors command, a valid architecture file, and an "./output".
      Then Gherkin feature files are written to an output directory.



